### ISSUE TITLE
Zabezpieczenie procesu rejestracji

### ISSUE THREAD

**Issue by rtpm** [ProteGO-Safe/backend#45]
Jeśli API byłoby dostępne, wysyłając odpowiedniego requesta na /register można komuś zrobić psikusa, gdyż nie ma możliwości walidacji numeru telefonu, który poda się w zgłoszeniu o rejestrację.

Rozważyć więc należy możliwość dodania pola adresu IP (wiem, kwestia prywatności..), z którego poszedł request rejestracji,
co da możliwość zastosowania jakiegoś throthlingu, a w razie czego blokowania/zgłoszenia dowcipnisia. Można też korzystać z unikalnego identyfikatora urządzenia/instalacji aplikacji, ale
to jest nieweryfikowalne i wiadomo, że to co leży na urządzeniu jest raczej "jawne" i do zmanipulowania poza aplikacją.

**Comment by mateuszjablonski** [comment]
Z czego wynika konieczność podania numeru telefonu? Czy jest to podyktowane jakimiś zewnętrznymi wymaganiami? W https://github.com/ProteGO-app/specs/issues/34 postulowane jest porzucenie konieczności podawania numeru telefonu, co całkowicie wyeliminowałoby ten problem.

**Comment by rtpm** [comment]
Rzeczywiście przegapiłem dokument, w którym przedstawione są już rozwiązania. Zastanawiam się, czy w proces samej rejestracji nie zaangażować jakiejś recaptcha (Jakiś WebView, co wymagałoby modyfikacji endpointa  lub tez schowania go gdzieś lub nie upubliczniania) a zastosować zwykły widok z danymi forma i tokenem captchy. Jeśli nie ma potrzeby żeby endpoint rejestracji był dostępny dla innych urządzeń itd. to można to rozważyć.

**Comment by jakublipinski** [comment]
Dzięki za wasze uwagi. Dodałem jeszcze takie zmiany https://github.com/ProteGO-app/backend/pull/52

Widzicie jeszcze jakieś ryzyka? Czy jesteśmy zabezpieczeni przed zgadywaniem kodów?

**Comment by kfigaj** [comment]
1. `Jeśli API byłoby dostępne` - API nie powinno być na pewno publicznie dostępne, tylko ograniczone do applikacji mobilnych Protego. W takiej sytuacji spamowanie ograniczamy do pobranych appek. Jest to trudniejsze do zapewnienia przy otwartym kodzie. Może coś takiego byłoby pomocne? Instancje applikacji można identyfikować po https://developers.google.com/instance-id Dalej ->
2. Jeśli ktoś z jednej istancji aplikacji próbuje rejestrować wiele numerów w określonym czasi- dostaje bana.
3. Jeśli ktoś próbuje zarejestrować kolejne instancje aplikacji, to dostaje bana.
4. Jeśli ktoś próbuje rejestrować użytkownika bez uprzedniego zarejestrowania instancji, to dostaje bana.
5. `W najgorszym wypadku, taka osoba dostanie kod autoryzacyjny, do którego dowcipniś nie będzie miał dostępu, a co za tym idzie nie dokończy procesu rejestracji`. Poza instancją applikacji można by się pokusić o wysłanie jakiegoś klucza publicznego. Kod autoryzacyjny mógłby wtedy być nim szyfrowany i tylko applikacja, która ma klucz prywatny może kod odkodować i użyć. Inne kody mogą zostać zignorowane po stronie aplikacj.
