### ISSUE TITLE
Mamy integrację z nową bramką SMS

### ISSUE THREAD

**Issue by jakublipinski** [ProteGO-Safe/backend#48]
Będzie nowa bramka SMS. Jak tylko dowiem się jaka, dam znać.

**Comment by rafbara** [comment]
@jakublipinski można prosić o jakieś dane dostępowe do bramki żeby potestować backend w całości ?

**Comment by jakublipinski** [comment]
@rafbara sorki, ale mamy tylko produkcyjna bramke. zrób sobie jakiś mock
