### ISSUE TITLE
Race condition w confirm_registration pozwalający na stworzenie kilku userów z tym samym msisdn

### ISSUE THREAD

**Issue by bartekn** [ProteGO-Safe/backend#50]
Wywołania `get` i `put` w `confirm_registration` nie znajdują się wewnątrz [transakcji](https://cloud.google.com/datastore/docs/concepts/transactions). Oznacza to, że przy wielokrotnym wywołaniu funkcji dla tych samych parametrów może dojść do stworzenia dwóch lub więcej instancji użytkownika w datastore. Przykład:

T | Request 1 | Request 2
-|-|-
1 | `_get_registration_entity(registration_id)` => `REGISTRATION_STATUS_PENDING` | 
2 | | `_get_registration_entity(registration_id)` => `REGISTRATION_STATUS_PENDING`
3| | `_update_registration(registration_entity, REGISTRATION_STATUS_COMPLETED)`
4 | `_update_registration(registration_entity, REGISTRATION_STATUS_COMPLETED)` |
5 | `_get_existing_user_id(registration_entity["msisdn"])` => `None` | 
6 | | `_get_existing_user_id(registration_entity["msisdn"])` => `None`
7 | `user_id = secrets.token_hex(32)` | `user_id = secrets.token_hex(32)`
8 | | `datastore_client.put(user)`
9 | `datastore_client.put(user)` (inny `user_id`) |

**Comment by jakublipinski** [comment]
Słusznie. Wielkie dzięki.
