### ISSUE TITLE
Dodawanie encounters w mniejszych paczkach aby zmieścić się w limitach GC

### ISSUE THREAD

**Issue by bartekn** [ProteGO-Safe/backend#62]
Na stronie [Quotas and Limits](https://cloud.google.com/bigquery/quotas#streaming_inserts) można znaleźć informację o maksymalnym rozmiarze requestu HTTP w przypadku Streaming inserts (używane przez `insert_rows`):
> HTTP request size limit: 10 MB (see Note)
> Exceeding this value will cause invalid errors.
> Note: Internally the request is translated from HTTP json into an internal data structure. The translated data structure has its own enforced size limit. It's hard to predict the size of the resulting internal data structure, but the chance of hitting the internal limit is very low if you keep your HTTP requests to 5 MB or less.

Oczywiście 5 MB to sporo i jest szansa że to nigdy się nie wydarzy (zależy jak działa aplikacja mobilna) ale myślę, że z uwagi na fakt, że te dane są niezwykle ważne i nie wiadomo kiedy i czy nastąpi retry warto rozważyć trzymanie się limitu 5 MB przy dodawaniu tych danych. W praktyce trzeba wywołać `insert_rows` kilka razy z mniejszymi paczkami.

_Originally posted by @bartekn in https://github.com/ProteGO-app/backend/pull/34/files_

**Comment by jakublipinski** [comment]
@bartekn ile `encounters` zmieści się w 5 MB?
