### ISSUE TITLE
Współdzielenie kodu między funkcjami

### ISSUE THREAD

**Issue by DariuszAniszewski** [ProteGO-Safe/backend#63]
Obecnie wiele funkcji zawiera duplikacje kodu - walidacja standardowych parametrów, pobieranie/aktualizowanie użytkowników w Datastore itp.

Wynika to ze specyfiki Cloud Functions które muszą być niezależne od siebie oraz posiadać plik `main.py` w głównym katalogu z funkcją. Nie ma możliwości importowania z plików będących poza katalogiem z plikiem `main.py`. 

Proponuję rozwiązanie polegające na utworzeniu pliku `utils.py` (przykładowo) w nadrzędnym folderze repozytorium. Plik ten zawierałby wspólne metody dla wszystkich funkcji. Plik byłby linkowany na poziomie deploymentu przez terraforma poprzez

1. utworzenie definicji pliku
```
data "local_file" "utils" {
  filename = "${path.module}/utils.py"
}
```

2. dodanie go przy tworzeniu pliku ZIP, np:
```
// START check_version
[...]
data "archive_file" "check_version" {
  type        = "zip"
  output_path = "${path.module}/files/check_version.zip"
  [...]
  source {
    content  = "${file("${data.local_file.utils.filename}")}"
    filename = "utils.py"
  }
}
```

W każdej funkcji wystarczy zaimportować metody z modułu zwykłym importem: 
`from utils import ...` 

Co ważne, lokalne środowisko nie musi być zmieniane - ustawiając katalog nadrzędny z tego repozytorium jako katalog nadrzędny projektu, wszystkie importy działają lokalnie, a zmiana jest tylko na poziomie terraforma do wdrożenia.

**Comment by rafbara** [comment]
@DariuszAniszewski ja popieram ten pomysł, brakuje tutaj jeszcze definicji modeli zgrupowanych w jednym miejscu lub w funkcjach. W planach jest aplikacja backoffice it tam bardzo by się to przydało.
