### ISSUE TITLE
Uruchamianie testów przy instalacji aplikacji

### ISSUE THREAD

**Issue by rafbara** [ProteGO-Safe/backend#73]
Po zainstalowaniu projektu i uruchomieniu go w GPC testy się nie ruchamiają.

python -m  unittest

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

**Comment by rafbara** [comment]
@jakublipinski przygotowałem zautomatyzowane środowisko dockera pod aplikację, można prosić o przydzielienie praw do zapisu repozytorium ?

**Comment by jakublipinski** [comment]
A gdzie można zobaczyć to co przygotowałeś? Dlaczego potrzebujesz write do repo? @rafbara

**Comment by rafbara** [comment]
@jakublipinski zrobiłem osobnego brancha i próbuje go wypchać do repozytorium ale nie mam uprawnień do zapisu.

**Comment by rafbara** [comment]
Problem uruchomienia testów był spowodowany wersją pythona. Na zaautomatyzowanym dockerowym środowisku testy działają jednak dalej nie przechodzą. 
Mam 2 wyniki - za drugim razem było 3 failure, 3errors natomiast za 1szym razem 16 errors. 
Będe to analizował zaraz po tym jak sprawdzę uruchamianie funkcji na gcloud.

**Comment by rafbara** [comment]
> A gdzie można zobaczyć to co przygotowałeś? Dlaczego potrzebujesz write do repo? @rafbara

file:/var/www/backend-master/backend/docker-compose.txt
file:/var/www/backend-master/backend/Dockerfile.txt

**Comment by jakublipinski** [comment]
Pracujemy w oparciu o pull-requests: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests Każda zmiana podlega "review" zanim zostanie zaakceptowana

**Comment by rafbara** [comment]
> Pracujemy w oparciu o pull-requests: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests Każda zmiana podlega "review" zanim zostanie zaakceptowana

jasne, zrobiłem sobie brancha lokalnie ponieważ nie mam uprawnień do tworzenia nowego brancha w tym repozytorium bez tych uprawnień nic nie mogę wysłać i tym bardziej utworzyć PR.

btw.
Mam dziwny problem jestem właścicielem projektu w gcloud a mimo to mam problem z uprawnieniami podczas instalacji scryptu na gcloud (funkcje w gcloud istnieją)
`Error applying IAM policy for cloudfunctions cloudfunction "projects/jcommerce-developers/locations/europe-west3/functions/send_register_sms": Error setting IAM policy for cloudfunctions cloudfunction "projects/jcommerce-developers/locations/europe-west3/functions/send_register_sms": googleapi: Error 403: Permission 'cloudfunctions.functions.setIamPolicy' denied on resource 'projects/jcommerce-developers/locations/europe-west3/functions/send_register_sms' (or resource may not exist).`
