### ISSUE TITLE
Podstawowa wersja CMS dla adminów

### ISSUE THREAD

**Issue by jakublipinski** [ProteGO-Safe/backend#8]
- [ ] Admin może zobaczyć nowych pacjentów i oznaczyć ich jako zweryfikowany / niezweryfikowany
- [ ] Admin może zobaczyć jakich użytkowników napotkał pacjent, kiedy, jak często i jaka była siła sygnału spotkani
- [ ] Admin wybiera i oznacza wybranych użytkowników jako `red`

**Comment by rafbara** [comment]
@jakublipinski mam doświadczenie we flask-admin, mogę pomóc w temacie.

**Comment by jakublipinski** [comment]
@rafbara wielkie dzieki. jeszcze potrzebujemy to wyspecyfikowac
