### ISSUE TITLE
Repozytorium nie zawiera kodu aplikacji

### ISSUE THREAD

**Issue by jasisz** [ProteGO-Safe/backend#82]
To repozytorium zawiera kod starej wersji aplikacji (od której funkcjonalnie nowa wprawdzie nie różni się prawie niczym), ale nie jest to kod, który jest odpalony na właściwym serwerze produkcyjnym ProteGO Safe.

Repozytorium powinno zostać zaktualizowane o nową wersję kodu, tak jak stało się to z repozytoriami android i ios.

Jeżeli kod backendu i alogrytmy określajace stan zagrożenia nie mają być publiczne - powinno być to wprost napisane w https://github.com/ProteGO-Safe/specs a to repozytorium powinno zostać usunięte, bo teraz wprowadza tylko w błąd.

**Comment by Tarvald** [comment]
@jasisz 
Przygotowywujemy update readme.md

Obecnie backend składa się mniej więcej z:

1. Nginx
2. https://github.com/opentrace-community/opentrace-cloud-functions master
3. Proxy do api.infermedica.com

Aczkolwiek backend jest w trakcie przebudowy.
