### ISSUE TITLE
limit_requests niepotrzebnie składuje adresy IP w bazie danych

### ISSUE THREAD

**Issue by qbolec** [ProteGO-Safe/backend#88]
Z tego co rozumiem, zakładamy, że ostatni człon w X-Forwarded-For jest wystarczająco precyzyjnie powiązany z człowiekiem, że warto go używać do karania spamerów.
(Zakładam, że wiemy to, bo sami ustawiamy ten nagłówek na krawędzi systemu by był równy IP z którego przychodzi request)
Następnie w oparciu o ten ip budujemy string używany jako klucz pod którym w Redisie trzymamy sobie ile requestów robiono do danej funkcji w danym okresie z danego ip:
```
    key = f"{function}:{period}:{ip}"
```
Wygląda na to, że dekoratora limit_request używamy w dość sensytywnej sądząc po nazwie funkcji `send_encounters` - dopiero zapoznaję się z projektem, więc mogę się mylić, ale nazwa brzmi jak coś czego się używa gdy się jest chorym i chce się przesłać na serwer listę spotkanych idików. 

A zatem, jeśli ktoś zajrzy do Redisa i poszuka sobie kluczy zaczynających się od prefixu `send_encounters:day:`, to czy przypadkiem nie dostanie na tacy adresów IP osób, które są z dużym ppb są chore, a przynajmniej sądzą, że są, a przynajmniej korzystały z endpointu send_encounters, a przynajmniej jakieś IP które uważamy za dostatecznie precyzyjnie powiązane z takimi ludźmi?

Z tego co rozumiem, nie ma potrzeby by klucz `key` był czytelny dla ludzi czy ogólnie "odwracalny" - wystarczy tylko by istniała funkcja różnowartościowa z krotek `(function,period,ip)` w takie stringi.
Oczywiście liczba różnych `function`, różnych `period` a nawet różnych `ip` jest bardzo mała, więc zwyczajnie zahashowanie tego nie wystarczy, bo mogę sobie bruteforcem przeglądnąć wszystkie takie krotki i sprawdzić, które z nich po zahashowaniu są kluczami w Redisie.

Nie wiem ile "instancji" tego serwera mamy i jak długowieczne one są, ale może wystarczyłoby, żeby serwer przy starcie losował sobie jakiś salt, znany tylko jemu tj. trzymany w jakiejś pythonowej zmiennej, którego będzie używał przez cały czas aż padnie, by solić hashe?

Alternatywnie, może mógłby ów salt być jakoś wstrzykiwany z zewnątrz przez jakiś Env - to nieco mniej bezpieczne, ale zakładam, że jak ktoś ma dostęp do tej części serwera ORAZ do Redisa, to jest to sytuacja o oczko gorsza niż jeśli ma dostęp tylko do Redisa (czy jego dumpów, backupów, komunikacji, logów?), więc jest postęp.

**Comment by Tarvald** [comment]
@qbolec 
Wygląda na to że, issue dotyczy starego kodu backendu który był wytwarzany zanim Open Trace oraz G+A ogłosili swoje rozwiązania.

Mieliśmy mały bałagan na GH.

Po więcej zapraszam tutaj #147 oraz tutaj https://github.com/ProteGO-Safe/backend.

Przepraszamy, za nieścisłości. 

Jeżeli problem nie dotyczy obecnej wersji, to bardzo byś nam pomógł zamykając to issue.

**Comment by qbolec** [comment]
Tak, to dotyczyło `limit_requests` w pliku rate_limit.py, który już usunęliście, tak więc zamykam.
