### ISSUE TITLE
nie działa Exposure Notifications Express

### ISSUE THREAD

**Issue by Buzzraider** [ProteGO-Safe/backend#97]
**Is your feature request related to a problem? Please describe.**
Czy zostanie wprowadzony Exposure Notifications Express, update na IOS już jest
**Describe the solution you'd like**
Wprowadzenie exposure notification express
**Describe alternatives you've considered**
b/d
**Additional context**
b/d

**Comment by tomekziel** [comment]
https://www.androidpolice.com/2020/09/01/apple-and-google-helping-health-authorities-make-quick-covid-tracking-apps-with-exposure-notifications-express/

"_Express, **currently targeted to just the U.S**., may be available in places where an ENS app with the Apple-Google API is already in place — that will be the case with Nevada and Virginia, both of which will be first adopters alongside the District of Columbia and Maryland._"

**Comment by Buzzraider** [comment]
Mhm rozumiem, ale jako ciekawostke podam, ze udało mi sie włączyć exposure notification bez instalacji protego safe na ios 13.7. Po wybraniu regionu polska, pojawilo mi sie protego.safe jako provider, a status exposure notification wlaczyl sie jako active (bez pobierania aplikacji ze sklepu) niestety zaczalem sie tym bawic wylaczyłem i juz ponownie nie udalo mi sie wlaczyc. Myslalem ze robicie jakies testy na backendzie i akurat wstrzeliłem sie w okno.

**Comment by pkleczko** [comment]
Nie jesteśmy póki co dostosowani do EN Express, na pewno docelowo będzie wymagało to integracji z infrastrukturą lokalnego PHA (Public Health Authority) i na ten moment jest więcej pytań niż odpowiedzi. Europa w przeciwieństwie do US wystartowała wcześniej z EN i wiele państw ma już własne aplikacje. Express w założeniu ma pomóc na szybsze uruchomienie EN i zbieranie kluczy podczas gdy organizacja Verification i Key Server'ów może dziać się równolegle. Dzięki temu stany, które nie mają swoich apek będą mogły nadgonić inne stany. Jak to będzie wyglądało w EU jest jeszcze niewiadomą i rozmawiamy z Google i Apple na ten temat.
